version = "Two"
max_width = 110
fn_single_line = true
where_single_line = true
array_layout = "Tall"
newline_style = "Unix"
group_imports = "StdExternalCrate"
indent_style = "Block"
wrap_comments = true
format_strings = false
imports_granularity = "Crate"